### ISSUE TITLE
Fréquentation par site

### ISSUE THREAD

**Issue by TTalex** [fabmob/meteo-mobilite-jo#11]
## Description de l'indicateur
Nombre et types de population se rendant sur les différents sites Olympiques. Corrélation par rapport à la dimension du site ?
Age, genre, CSP etc... seraient intéressants, par site et par type de sport.

## Source de l'indicateur
- ⬜ Interne
- ✅ Feedback partenaire / Atelier
- ⬜ Indicateur existant
- ⬜ Autre

## Illustrations, sources d'inspiration
![niveau de vie moyen au carreau](https://github.com/fabmob/meteo-mobilite-jo/assets/7023229/a18b55a0-b440-4b46-90ab-bf0d1899080e)
> Source: https://diagnostic-mobilite.fr/app/

## Détails techniques
* Biais dans la population source (français uniquement)
* Nécessite des info personnelles en plus des infos de déplacements

**Comment by ghislainfabmob** [comment]
Axes éditoriaux :
- "Les français sont-ils chauvins"
-
